"""Add AIJob and Notification models

Revision ID: 271f844c4a8b
Revises: 8472d213561d
Create Date: 2026-04-17 23:54:24.135107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '271f844c4a8b'
down_revision: Union[str, None] = '8472d213561d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_jobs', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('ai_jobs', sa.Column('retries', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('ai_jobs', 'job_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('ai_jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('ai_jobs', 'celery_task_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('idx_ai_jobs_artwork_id', 'ai_jobs', ['artwork_id'], unique=False)
    op.create_index('idx_ai_jobs_status', 'ai_jobs', ['status'], unique=False)
    op.drop_column('ai_jobs', 'error_message')
    op.drop_column('ai_jobs', 'attempts')
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('notifications', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('idx_notifications_user_read'), table_name='notifications')
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.add_column('orders', sa.Column('artwork_id', sa.UUID(), nullable=False))
    op.add_column('orders', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('orders', sa.Column('shipping_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('orders_stripe_session_id_key'), 'orders', type_='unique')
    op.create_index('idx_orders_artwork_id', 'orders', ['artwork_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'artworks', ['artwork_id'], ['id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('stripe_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index('idx_orders_artwork_id', table_name='orders')
    op.create_unique_constraint(op.f('orders_stripe_session_id_key'), 'orders', ['stripe_session_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.create_index(op.f('idx_notifications_user_read'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.alter_column('notifications', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('audit_logs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('artworks', sa.Column('ai_medium_suggestion', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('artworks', sa.Column('ai_tags_suggestion', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('artworks', sa.Column('ai_generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('artworks', sa.Column('ai_price_suggestion', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('artworks', sa.Column('ai_description_suggestion', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('artworks', sa.Column('ai_style_suggestion', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('artworks', sa.Column('ai_title_suggestion', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('artworks', sa.Column('ai_price_confidence', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('artist_profiles', sa.Column('verification_submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('artist_profiles', sa.Column('verification_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('artist_profiles', sa.Column('verification_status', sa.VARCHAR(length=50), server_default=sa.text("'unverified'::character varying"), autoincrement=False, nullable=False))
    op.add_column('ai_jobs', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ai_jobs', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('idx_ai_jobs_status', table_name='ai_jobs')
    op.drop_index('idx_ai_jobs_artwork_id', table_name='ai_jobs')
    op.alter_column('ai_jobs', 'celery_task_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('ai_jobs', 'status',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('ai_jobs', 'job_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('ai_jobs', 'retries')
    op.drop_column('ai_jobs', 'error')
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cart_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('artwork_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price_at_add', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], name=op.f('cart_items_artwork_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('cart_items_cart_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_items_pkey')),
    sa.UniqueConstraint('cart_id', 'artwork_id', name=op.f('uq_cart_items_cart_artwork'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('artwork_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('price_paid', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('title_snapshot', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], name=op.f('order_items_artist_id_fkey')),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], name=op.f('order_items_artwork_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_items_order_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('order_items_pkey'))
    )
    op.create_table('carts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('buyer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('carts_buyer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('carts_pkey')),
    sa.UniqueConstraint('buyer_id', name=op.f('carts_buyer_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stripe_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('transactions_order_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_table('system_settings',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('system_settings_pkey'))
    )
    # ### end Alembic commands ###
