"""add_orders_table

Revision ID: 8472d213561d
Revises: 0001_phase1
Create Date: 2026-04-13 12:41:37.113246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8472d213561d'
down_revision: Union[str, None] = '0001_phase1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('artwork_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('shipping_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled')", name='orders_status_check'),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_artwork_id', 'orders', ['artwork_id'], unique=False)
    op.create_index('idx_orders_buyer_id', 'orders', ['buyer_id'], unique=False)
    op.drop_index(op.f('idx_artist_profiles_user_id'), table_name='artist_profiles')
    op.drop_index(op.f('idx_artwork_images_artwork_id'), table_name='artwork_images')
    op.drop_index(op.f('idx_artwork_tags_tag_id'), table_name='artwork_tags')
    op.drop_index(op.f('idx_artworks_category_id'), table_name='artworks')
    op.drop_index(op.f('idx_artworks_created_at'), table_name='artworks')
    op.drop_index(op.f('idx_artworks_deleted_at'), table_name='artworks', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_artworks_price'), table_name='artworks')
    op.drop_index(op.f('idx_artworks_search'), table_name='artworks', postgresql_using='gin')
    op.drop_index(op.f('idx_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'created_at')
    op.drop_index(op.f('idx_buyer_profiles_user_id'), table_name='buyer_profiles')
    op.drop_index(op.f('idx_favorites_user_id'), table_name='favorites')
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_index(op.f('idx_users_supabase_user_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_supabase_user_id'), 'users', ['supabase_user_id'], unique=True)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_index(op.f('idx_buyer_profiles_user_id'), 'buyer_profiles', ['user_id'], unique=False)
    op.add_column('audit_logs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_entity'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_artworks_search'), 'artworks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_artworks_price'), 'artworks', ['price'], unique=False)
    op.create_index(op.f('idx_artworks_deleted_at'), 'artworks', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_artworks_created_at'), 'artworks', ['created_at'], unique=False)
    op.create_index(op.f('idx_artworks_category_id'), 'artworks', ['category_id'], unique=False)
    op.create_index(op.f('idx_artwork_tags_tag_id'), 'artwork_tags', ['tag_id'], unique=False)
    op.create_index(op.f('idx_artwork_images_artwork_id'), 'artwork_images', ['artwork_id'], unique=False)
    op.create_index(op.f('idx_artist_profiles_user_id'), 'artist_profiles', ['user_id'], unique=False)
    op.drop_index('idx_orders_buyer_id', table_name='orders')
    op.drop_index('idx_orders_artwork_id', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
