"""0003_phase2_commerce

Revision ID: fcb4ba4350e9
Revises: 8472d213561d
Create Date: 2026-04-13 17:32:03.269718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcb4ba4350e9'
down_revision: Union[str, None] = '8472d213561d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('artwork_id', sa.UUID(), nullable=False),
    sa.Column('price_at_add', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('added_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'artwork_id', name='uq_cart_items_cart_artwork')
    )
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('artwork_id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('title_snapshot', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stripe_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artist_profiles', sa.Column('verification_status', sa.String(length=50), server_default='unverified', nullable=False))
    op.add_column('artist_profiles', sa.Column('verification_submitted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('artist_profiles', sa.Column('verification_notes', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('orders', sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    # Add as nullable first so existing rows don't fail
    op.add_column('orders', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # Backfill from existing 'amount' column before dropping it
    op.execute("UPDATE orders SET total_amount = amount WHERE total_amount IS NULL")
    op.execute("UPDATE orders SET currency = 'USD' WHERE currency IS NULL")
    # Now enforce NOT NULL
    op.alter_column('orders', 'total_amount', nullable=False)
    op.alter_column('orders', 'currency', nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('idx_orders_artwork_id'), table_name='orders')
    op.create_unique_constraint(None, 'orders', ['stripe_session_id'])
    op.drop_constraint(op.f('orders_artwork_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'amount')
    op.drop_column('orders', 'artwork_id')
    op.drop_column('orders', 'shipping_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('artwork_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('orders_artwork_id_fkey'), 'orders', 'artworks', ['artwork_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='unique')
    op.create_index(op.f('idx_orders_artwork_id'), 'orders', ['artwork_id'], unique=False)
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'currency')
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'stripe_payment_intent_id')
    op.drop_column('orders', 'stripe_session_id')
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('artist_profiles', 'verification_notes')
    op.drop_column('artist_profiles', 'verification_submitted_at')
    op.drop_column('artist_profiles', 'verification_status')
    op.drop_table('transactions')
    op.drop_table('order_items')
    op.drop_table('cart_items')
    op.drop_index('idx_notifications_user_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('carts')
    # ### end Alembic commands ###
